# Generated by Django 5.2.7 on 2025-10-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
    ]
