# Generated by Django 5.2.7 on 2025-10-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
